VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE ?= yes

NKRO_ENABLE = no
MOUSE_SHARED_EP = no
EXTRAKEY_ENABLE = no
STENO_ENABLE = no
VIRTSER_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

ifneq ($(findstring -DINIT_EE_HANDS_RIGHT,$(OPT_DEFS)),)
MOUSE_SHARED_EP = yes
VIA_ENABLE  = no
VIAL_ENABLE = no
RAW_ENABLE  = no
endif
